pnxenopoulos/awpy

README.md
Fixing issue brought up in #15
=> Updated python requirement in README from 3.6 to 3.7

csgo/parser/parse_demo.go
Fixing issue brought up in #14
=> Updated parse_demo.go to allow parse_rate = 0

.github/workflows/codeql-analysis.yml, README.md
Adding one liner to README on new `dev` branch, as well as a codeql workflow.
=> Adding dev info to README and codeql

csgo/parser/demoparser.py, csgo/parser/parse_demo.go
Fixed an issue arising from the `isTrade` function brought up by `lakshyaag#6558` on Discord. Also changed bombsite parsing on bomb events to be more stable.
=> isTrade fix, bombsite fixes

csgo/visualization/plot.py
=> Fixing coord translation error

.github/workflows/build.yml, csgo/parser/demoparser.py, csgo/parser/parse_demo.go
- Adding UTF8 to JSON write method, outlined by JanEric1#4107
- Fixing bot naming error raised by Charmees#0250
- Adding pycov
=> JSON encoding, bot name error, pycov

csgo/parser/parse_demo.go, tests/test_data.json, tests/test_demo_parse.py
Added test for issue raised by Charmees
=> Adding test for bot name

csgo/parser/demoparser.py, csgo/parser/parse_demo.go, tests/test_data.json, tests/test_demo_parse.py
Adding to clean rounds by editing warmup checker.
=> Warmup fix

csgo/parser/demoparser.py, csgo/parser/parse_demo.go
=> Clean rounds changes

awpy/analytics/stats.py, awpy/parser/demoparser.py, awpy/parser/parse_demo.go, docs/parser_output.rst, setup.py, tests/test_demo_parse.py
- Fixing player side to update on each frame (reborn in Discord)
- Making `remove_bad_scoring=True` by default
- Fixing issue in #158
=> Player side, round scoring, div by 0

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/build.yml, README.md, awpy/analytics/__init__.py, awpy/parser/demoparser.py, awpy/parser/parse_demo.go, awpy/utils.py, docs/index.rst, docs/installation.rst, docs/parser_output.rst, setup.py, tests/test_demo_parse.py
- Fix 1.17 requirement
- Rework world objects to projectiles, bomb, inferno, fires
- Fix player stats issue
- Fix buy type / eq val / spend
- Fix T current eq val in frames
- Documentation changes
=> fixing 1.17, world obj, spend/buy/eqval

awpy/parser/parse_demo.go, docs/conf.py, setup.py
Added expanded player info:
- eye position
- isbot flag
- last place name
- grenade counts
=> Awpy 1.1.9

awpy/parser/demoparser.py, tests/test_demo_parse.py
Fixes https://github.com/pnxenopoulos/awpy/issues/199 and extends tests coverage to those scenarios.
=> Fixed bug when trying to infer demoid from windows file paths

.gitignore, awpy/analytics/stats.py, awpy/parser/parse_demo.go, tests/test_stats.py
Fixes https://github.com/pnxenopoulos/awpy/issues/183
=> Fixing issue with player statistics when a player changed their name mid game. Adding more metrics to player statistics

.github/workflows/build.yml, awpy/analytics/nav.py, awpy/analytics/states.py, awpy/analytics/stats.py, awpy/analytics/wpa.py, awpy/data/__init__.py, awpy/parser/cleaning.py, awpy/parser/demoparser.py, awpy/types.py, awpy/utils.py, awpy/visualization/plot.py, tests/test_nav.py
I added type hinting to the current main branch.
I also expanded some function doc strings to include all the errors they raise where those were missing.
Additionally i expanded the github workflow to run linting with flake8 and type checking with mypy.
=> Added type hinting

awpy/parser/demoparser.py, awpy/parser/parse_demo.go, awpy/types.py, awpy/utils.py, tests/test_demo_parse.py, tests/test_stats.py, tests/test_utils.py, tests/test_vis.py
Compiled chatMessages, SayText and SayText2 into a Chat Object for the output of the parse function
=> Support for chatMessages, SayText and SayText2

.github/workflows/go_code.yml, .golangci.yaml, pyproject.toml, requirements.txt, setup.py, tests/requirements.txt
To avoid regressions from updated dependencies like in https://github.com/pnxenopoulos/awpy/issues/236
=> Fixing requirements to tighter bounds

.golangci.yaml, awpy/parser/parse_demo.go
Fixes errors like: https://pastebin.com/nf0Qxe51
=> Fixing go bug with accessing nil pointer for grenades in old demos.

pyproject.toml, setup.py
Got a report on discord that the current pyproject.toml breaks build on colab.
=> Updating pyproject.toml and setup.py to be consistent with requirements.txt

awpy/analytics/stats.py
Currently can happen due to player dis- and reconnecting. Triggering clutching logic already at 2 players alive instead of 1. At 1 player alive it is retriggered and no clutcher can be found causing a KeyError. Now the rest of the clutching logic is simply skipped. Incorrect clutching stats remain.
=> Skipping clutching logic if no clutcher can be found.

.github/workflows/build.yml, tests/conftest.py, tests/test_data.json, tests/test_demo_parse.py, tests/test_states.py, tests/test_stats.py, tests/test_wpa.py
Changed the test demo locations to mediafire to be easier on my GCP budget
=> fixed test locations

awpy/parser/parse_demo.go, awpy/types.py, tests/conftest.py, tests/test_data.json, tests/test_demo_parse.py
=> fix some nils for POV demos

.github/workflows/build.yml, .pre-commit-config.yaml, awpy/analytics/nav.py, awpy/types.py, pyproject.toml, tests/requirements.txt
Updated linters in CI and pre-commit.
Added perflint rules to ruff configuration and fixed one raised warning.
=> Updated linters.

awpy/analytics/map_control.py, awpy/analytics/nav.py, awpy/data/__init__.py, awpy/types.py, awpy/utils.py, awpy/visualization/plot.py, tests/test_map_control.py, tests/test_nav.py
First commit propagates `TileId`. Please check that i didnt put it somewhere where it doesnt belong and that i didnt miss any where it does.
closes https://github.com/pnxenopoulos/awpy/issues/240
=> Propagate map control types throughout awp

awpy/analytics/map_control.py, awpy/visualization/plot.py
Some map control functions have some docs related errors (outlined in [this GitHub Issue](https://github.com/pnxenopoulos/awpy/issues/279)). This commit should help fixing those errors and others I noticed.
=> Addressing documentation issues with some map control related functions

awpy/data/map/README.md
=> updated map data readme

awpy/parser/parse_demo.go
Fixed a bug introduced in https://github.com/pnxenopoulos/awpy/pull/239.
Caught by @JuhaKiili here: https://github.com/pnxenopoulos/awpy/commit/a2d18f3904b6694bae1c2fcb4866ccd34c3c85fe#r128607841
=> Properly set projectile values again.

awpy/parsers.py
Just disabled it as mentioned. Tested on the 200 latest hltv demos and everything is now parsing as it should.
=> Fix user_is_strafing not in index

awpy/visibility.py, scripts/generate-tris.ps1
Changed the vphys extraction to not use the `world_physics.vphys` anymore which is deprecated but instead the `PHYS` section of `world_physics.vmdl_c`.
Additionally i fixed a small typo in the mesh extraction and further more corrected the used `m_nCollisionAttributeIndex` to be those actually pointing to "Default" grouped `collisionAttributes` instead of using the first, which may or may not be a default one and definitely may not be the only one.
=> Fixed vphys extraction and parsing
